[package]
name = "tortuga"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["full"] }
reqwest = { version = "0.12.7", features = ["json"] }
tower = "0.5.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"